version: "3.7"
services:
  finite:
    container_name: finite
    build: .
    image: factomproject/finite:localdev
    depends_on:
      - walletd
    ports:
      - "50051:50051"
    environment:
      PGUSER: pflow
      PGPASSWORD: pflow
      PGDATABASE: pflow
      PGHOST: pgsql
    networks:
      ptnet: {}
  walletd:
    container_name: walletd
    image: factominc/factom-walletd:latest
    depends_on:
      - factomd
    expose:
      - "8089"
    ports:
      - "8089:8089"
    volumes: []
    #- ./factom-data:/root/.factom/:rw
    command: -s=factomd:8088
    networks:
      ptnet: {}
  factomd:
    container_name: factomd
    image: factominc/factomd:latest
    expose:
      - "8088"
      - "8110"
      - "8090"
      - "9876"
    ports:
      - "8088:8088"
      - "8110:8110"
      - "8090:8090"
      - "9876:9876"
    volumes: []
    #- ./factom-data:/root/.factom/:rw
    command: -network=LOCAL
    networks:
      ptnet: {}
networks:
    ptnet:
      ipam:
        driver: default
        config:
          - subnet: 10.8.0.0/16
